services:
  database:
    build:
      context: ./src/database
      dockerfile: Dockerfile
    container_name: database
    env_file: ./src/database/.env
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - database
    restart: always

  app:
    build:
      context: ./src/app
      dockerfile: Dockerfile
    container_name: app
    depends_on: 
      - database
    env_file: ./src/app/.env
    restart: always
    networks:
      - database
    ports:
      - "80:80"

networks:
  database: