name: Test CTF Integration Requirements

on:
  push: # this runs automatically on push, I recommend turning off email notifs for failed runs :)
  workflow_dispatch: # allows you to manually trigger a run from web ui
  workflow_call: # allows this to be called by another repo

jobs:
  test-container:
    runs-on: ubuntu-latest

    steps:
      # This action gets your source code from the repo, and puts it into the container.
      # If you remove this, you will not be able to run the following steps (don't remove).
      - name: Checkout code
        uses: actions/checkout@v4

      # This command builds your docker environment.
      # We require all challenges to be made with docker compose so we can 
      # integrate them into the challenge infrastructure.
      # 
      # If this fails, double check that you are able to successfully run docker compose locally.
      # Also, you can check the logs in the github runner to see why the build failed.
      - name: Build Challenge (docker compose)
        run: |
          make deploy

      # Here, we run your programmatic solution to your challenge.
      # Feel free to use the provided example as inspiration!
      #
      # Use whatever format/langauge you like, but it must meet the following requirements
      # - Must reproducably test the full exploit chain. (Ensuring it works)
      #   - Ex: SQLi challenge, make a script that will make requests to your endpoint and end up with the flag
      #   - See attached example for inspiration on how to do this.
      # - Must echo the flag to STDOUT, this is how we know your challenge works.
      #
      # If your challenge solution can not be solved programmatically, speak to Dr. Kapravelos.
      # There are some challenges (forensics, special tooling, etc) that will not work with this format,
      # but short of a few exceptions, you should aim to have a functional solution script.
      #
      - name: Test Challenge Solution
        run: |
          FLAG_SUBSTR="hackpackCTF{"
          
          # We expect the string: `hackpackCTF{...}` as the output
          OUTPUT=$(make poc)
          echo $OUTPUT
          
          OUTPUT=${OUTPUT:0:12} # extract first 12 chars
          
          # This is a basic check. We know you can trivially bypass this. Do not.
          # If you come to us without a working PoC, we will consider your challenge incomplete.
          
          if [ "$OUTPUT" = "$FLAG_SUBSTR" ]; then
              echo "PoC successful!"
              exit 0
          else
              echo "PoC failed, check CI/CD logs."
              exit 1
          fi


      # Here we run your unit tests.
      # You are responsible for writing high quality unit tests, we will be manually reviewing these.
      # You should be comphrensively testing your application, trying to cover all functionality.
      # 
      # You should only print "Tests Passed" if your tests all succeed.
      # This step simply looks for the string "Tests Passed" with no other content.
      - name: Run Unit Tests
        run: |
          TEST_PASS="Tests Passed"

          OUTPUT=$(make test)
          
          OUTPUT=${OUTPUT:0:12} # extract first 12 chars

          # This is a basic check. We know you can trivially bypass this. Do not.
          # If you come to us without a working PoC, we will consider your challenge incomplete.
          
          if [ "$OUTPUT" = "$TEST_PASS" ]; then
              echo "Unit tests successful!"
              exit 0
          else
              echo "Unit test failed, check CI/CD logs."
              exit 1
          fi