name: Test CTF Integration Requirements

on:
  push: # this runs automatically on push, I recommend turning off email notifs for failed runs :)
  workflow_dispatch: # allows you to manually trigger a run from web ui

jobs:
  test-container:
    # If this step fails, you do not have access to the hackpack-ctf2025 repo.
    # Message @kapravel to get access.
    uses: hackpack-ncsu/hackpack-ctf2025-public/.github/workflows/challenge.yml@main